// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"mediverse/internal/models"
)

func RegisterModels() {
	resource.RegisterModels(
		&models.Doctors{},
		&models.RolePermissions{},
		&models.Schedules{},
		&models.UserRoles{},
	)
}
