PROJECT_NAME: mediverse
PROJECT_ID: hlptyhqudwlewwckotax
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_fa581a6e0cef39aff6f0c5d1bb22cd70f94a10ad
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhscHR5aHF1ZHdsZXd3Y2tvdGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1ODEzODEsImV4cCI6MjA0OTE1NzM4MX0.FVLuJ6vVJoT6hy1bxDxvaWSqXH3g4nmmYyhJlGYkZys
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhscHR5aHF1ZHdsZXd3Y2tvdGF4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMzU4MTM4MSwiZXhwIjoyMDQ5MTU3MzgxfQ.QVmOm5UYjegmcKr2Z1bwWN_ivoMbj035pXiaiJ3lZ7s

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://hlptyhqudwlewwckotax.supabase.co

SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
