PROJECT_NAME: be-medpoint
PROJECT_ID: bpulkteqsfswvhhwumhi
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN: sbp_968c0d055a93dbff3bc35e4d58ace833973e3abe
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwdWxrdGVxc2Zzd3ZoaHd1bWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2MjIyMTcsImV4cCI6MjA0ODE5ODIxN30.TyPvIq4oCcnTmwvJ4cU8lHTwojdrm4_ZLfnbucQwqck
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwdWxrdGVxc2Zzd3ZoaHd1bWhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI2MjIyMTcsImV4cCI6MjA0ODE5ODIxN30.TyPvIq4oCcnTmwvJ4cU8lHTwojdrm4_ZLfnbucQwqck

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://bpulkteqsfswvhhwumhi.supabase.co

SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
